name: goldfish
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.2=pyhd8ed1ab_0
  - boltons=23.1.1=pyhd8ed1ab_0
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.25.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.11.0=py39hf3d152e_1
  - conda-libmamba-solver=23.12.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - cudatoolkit=11.8.0=h4ba93d1_12
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - distro=1.9.0=pyhd8ed1ab_0
  - faiss=1.7.4=py39cuda112h460e57a_0_cuda
  - fmt=10.1.1=h00ab1b0_1
  - freetype=2.12.1=h267a509_2
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py39hf3d152e_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=8.5.0=hca28451_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libfaiss=1.7.4=cuda112hb18a002_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=20_linux64_openblas
  - libmamba=1.5.6=had39da4_0
  - libmambapy=1.5.6=py39h10defb6_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsolv=0.7.27=hfc55251_0
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.3=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - menuinst=2.0.1=py39hf3d152e_0
  - ncurses=6.4=h59595ed_2
  - nettle=3.3=0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pip=23.3.2=pyhd8ed1ab_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py39hd1e30aa_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h0755675_1_cpython
  - python_abi=3.9=4_cp39
  - readline=8.2=h8228510_1
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel.yaml=0.18.5=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39hd1e30aa_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.1=pyhd8ed1ab_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - x264=1!152.20180717=h14c3975_1001
  - xz=5.2.6=h166bdaf_0
  - yaml-cpp=0.8.0=h59595ed_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py39h6e5214e_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - accelerate==0.25.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioprometheus==23.12.0
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-doc==0.0.3
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bidict==0.23.1
      - bitsandbytes==0.37.2
      - blinker==1.9.0
      - braceexpand==0.1.7
      - chardet==5.2.0
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - decord==0.6.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - fastapi==0.121.0
      - ffmpy==0.6.4
      - filelock==3.19.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flask-socketio==5.5.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==3.50.2
      - gradio-client==0.6.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - more-itertools==10.8.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - narwhals==2.10.2
      - networkx==3.2.1
      - ninja==1.13.0
      - nltk==3.9.2
      - nodejs-wheel-binaries==22.20.0
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - openai==2.7.1
      - openai-whisper==20250625
      - opencv-python==4.11.0.86
      - orjson==3.11.4
      - pandas==2.3.3
      - peft==0.6.0
      - pillow==10.4.0
      - portalocker==3.2.0
      - proglog==0.1.12
      - progressbar2==4.5.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==5.9.8
      - pyarrow==21.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pydantic==1.10.13
      - pydub==0.25.1
      - pyparsing==3.2.5
      - pysrt==1.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.12.3
      - python-multipart==0.0.20
      - python-socketio==5.14.3
      - python-utils==3.9.1
      - pytubefix==10.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - quantile-python==1.1
      - ray==2.51.1
      - referencing==0.36.2
      - regex==2025.11.3
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.43.0
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - spaces==0.42.1
      - starlette==0.49.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tiktoken==0.12.0
      - timm==1.0.22
      - tokenizers==0.15.2
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - transformers==4.38.0
      - triton==3.3.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - visual-genome==1.1.1
      - vllm==0.2.5
      - wandb==0.22.3
      - watchfiles==1.1.1
      - webdataset==0.2.100
      - websockets==11.0.3
      - webvtt-py==0.5.1
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - xformers==0.0.31.post1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/ng204/anaconda3/envs/goldfish
